# Generated by Django 3.2 on 2021-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='floor_number',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default='7'),
            preserve_default=False,
        ),
    ]
