# Generated by Django 3.2 on 2021-05-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20210502_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetings.room'),
            preserve_default=False,
        ),
    ]
